### ISSUE TITLE
it crashes when i click "play"

### ISSUE THREAD

**Issue by zazazazer** [weespin/WillFromAfarDownloader#29]
i open it, put the text, select the voice and click play, then it crashes. what do i do?

**Comment by jcherr** [comment]
Same here, I'm getting an issue where it freezes for a bit then pulls up the same error that was posted by Sheepofthesouth back in December. It was working a few days before.

**Comment by jmd28** [comment]
I had a quick look into this yesterday, the _SynthesizerEndpoint which this tool uses (hosted on acapela-group) seems to be down. The _NonceEndpoint still works, but the_SynthesizerEndpoint times out...

**Comment by AustinTheSuperiorVyonder2021** [comment]
I am having a large issue with this. I opened it, put the text in, selected the voice I wanted to use and then clicked play, but the moment I tried hearing it, it crashed. I even had to perform a hard reset because of it and it's still broken. Please fix it.

**Comment by Kawaii123456** [comment]
i opened it to use it for a project i was working on, selected the voice i wanted to us.....only for the text to not play and then crash on me, i tried everything i could to fix it, but was unable to, please fix it.

**Comment by weespin** [comment]
Its look like they've changed the API. Investigating...

**Comment by weespin** [comment]
Found a fix! Will commit/release today

**Comment by weespin** [comment]
Fixed in https://github.com/weespin/WillFromAfarDownloader/commit/bd74283aaca4db00378b215f8597a2dc73a2d5d3
I didn't even know this program was being used! Thank you all! If you have any suggestions for improving the program, create a new issue or pull request!

**Comment by Kawaii123456** [comment]
It's working for me now ^_^ thank you so much for your help!

**Comment by AustinTheSuperiorVyonder2021** [comment]
Thank you so much. It works for me now too.

**Comment by WaleedAnimate2020** [comment]
When I select a voice to play or download it gave me an error from Microsoft net framework which it says

"Unhandled exception has occured in your application. If you click continue, the application will ignore this error and attempted to continue. If you click quit, the application will close immediately. Unable to connect the remote server.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 5.196.115.220:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at AcapellaDownloader.Utils.GetSoundLink(String text, String voiceid) in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Utils.cs:line 68
   at AcapellaDownloader.Form1.GetGUISoundLink() in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Form1.cs:line 132
   at AcapellaDownloader.Form1.btnPlay_Click(Object sender, EventArgs e) in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Form1.cs:line 145
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///D:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AcapellaDownloader
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/WINDOW~1.000/Users/User/DOWNLO~1/ACAPEL~1/ACAPEL~1.EXE
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NAudio
    Assembly Version: 1.10.0.0
    Win32 Version: 1.10.0.0
    CodeBase: file:///C:/WINDOW~1.000/Users/User/DOWNLO~1/ACAPEL~1/NAudio.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

How can I fix it?
